### ISSUE TITLE
Allow more than 1 IP

### ISSUE THREAD

**Issue by ijustateacrayon** [expertasolutions/AzDo.AzureDNSZoneExtensions#80]
How would we allow more than 1 IP for a single A record?

**Comment by lturmel** [comment]
Hi @ijustateacrayon, sorry for responding really lately. Unfortunately, I didn't design the extension to do such things (my bad). Since that time, I simply move away from Azure DevOps and moved to GitHub Actions.
I can take a look about what I can do for this extension, but this will take some time, because I'm currently very busy on some others works. I will let you known in couple of days/week
